apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-product-hub.operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "data-product-hub.name" . }}
    app.kubernetes.io/component: operator
