{{- if .Values.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ if .Values.data.pvc.name }}{{ .Values.data.pvc.name }}{{ else }}{{ include "data-product-hub.fullname" . }}-data{{ end }}
  labels:
    {{- include "data-product-hub.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.data.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.data.pvc.size | default "10Gi" }}
  {{- if .Values.data.pvc.storageClassName }}
  storageClassName: {{ .Values.data.pvc.storageClassName }}
  {{- end }}
{{- end }}
