apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-product-hub.fullname" . }}
  labels:
    {{- include "data-product-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
      protocol: TCP
  selector:
    {{- include "data-product-hub.selectorLabels" . | nindent 4 }}
